# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'orderSZOkPZ.ui'
##
## Created by: Qt User Interface Compiler version 5.15.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(593, 353)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(-10, 0, 461, 331))
        self.widget = QWidget()
        self.widget.setObjectName(u"widget")
        self.label_2 = QLabel(self.widget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(0, 0, 181, 141))
        self.label_2.setPixmap(QPixmap(u"jok_l.jpg"))
        self.label_2.setScaledContents(True)
        self.label = QLabel(self.widget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 150, 181, 141))
        self.label.setPixmap(QPixmap(u"images.jpeg"))
        self.label.setScaledContents(True)
        self.label_6 = QLabel(self.widget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(200, 0, 131, 51))
        font = QFont()
        font.setPointSize(32)
        self.label_6.setFont(font)
        self.label_6.setScaledContents(True)
        self.label_7 = QLabel(self.widget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(200, 150, 131, 51))
        self.label_7.setFont(font)
        self.label_7.setScaledContents(True)
        self.label_9 = QLabel(self.widget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(200, 220, 111, 31))
        font1 = QFont()
        font1.setPointSize(20)
        font1.setItalic(True)
        self.label_9.setFont(font1)
        self.label_10 = QLabel(self.widget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(200, 70, 111, 31))
        self.label_10.setFont(font1)
        self.pushButton_3 = QPushButton(self.widget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(330, 270, 111, 25))
        self.radioButton = QRadioButton(self.widget)
        self.radioButton.setObjectName(u"radioButton")
        self.radioButton.setGeometry(QRect(340, 50, 112, 23))
        self.radioButton_2 = QRadioButton(self.widget)
        self.radioButton_2.setObjectName(u"radioButton_2")
        self.radioButton_2.setGeometry(QRect(330, 200, 112, 23))
        self.tabWidget.addTab(self.widget, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.label_3 = QLabel(self.tab_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(50, 10, 51, 111))
        self.label_3.setPixmap(QPixmap(u"\uc9c4\ub85c.jpg"))
        self.label_3.setScaledContents(True)
        self.label_4 = QLabel(self.tab_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(50, 150, 51, 131))
        self.label_4.setPixmap(QPixmap(u"\ucc38\uc774\uc2ac.jpeg"))
        self.label_4.setScaledContents(True)
        self.label_13 = QLabel(self.tab_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(120, 10, 201, 51))
        self.label_13.setFont(font)
        self.label_13.setScaledContents(True)
        self.label_14 = QLabel(self.tab_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(130, 170, 171, 51))
        self.label_14.setFont(font)
        self.label_14.setScaledContents(True)
        self.label_11 = QLabel(self.tab_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(180, 80, 111, 31))
        self.label_11.setFont(font1)
        self.label_12 = QLabel(self.tab_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(180, 240, 111, 31))
        self.label_12.setFont(font1)
        self.pushButton = QPushButton(self.tab_2)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(330, 270, 111, 25))
        self.radioButton_3 = QRadioButton(self.tab_2)
        self.radioButton_3.setObjectName(u"radioButton_3")
        self.radioButton_3.setGeometry(QRect(320, 60, 112, 23))
        self.radioButton_4 = QRadioButton(self.tab_2)
        self.radioButton_4.setObjectName(u"radioButton_4")
        self.radioButton_4.setGeometry(QRect(310, 220, 112, 23))
        self.tabWidget.addTab(self.tab_2, "")
        self.listWidget_cart = QListWidget(self.centralwidget)
        self.listWidget_cart.setObjectName(u"listWidget_cart")
        self.listWidget_cart.setGeometry(QRect(450, 30, 141, 301))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label_2.setText("")
        self.label.setText("")
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\uc871\ubc1c \uc911 ", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\uc871\ubc1c \ub300", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u" 42000\uc6d0", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u" 36000\uc6d0", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"\uc8fc\ubb38", None))
        self.radioButton.setText(QCoreApplication.translate("MainWindow", u"\uc871\ubc1c \uc911", None))
        self.radioButton_2.setText(QCoreApplication.translate("MainWindow", u"\uc871\ubc1c  \ub300", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), QCoreApplication.translate("MainWindow", u"\uc871\ubc1c", None))
        self.label_3.setText("")
        self.label_4.setText("")
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"       \uc9c4\ub85c", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"    \ucc38\uc774\uc2ac", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u" 5000\uc6d0", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u" 5000\uc6d0", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"\uc8fc\ubb38", None))
        self.radioButton_3.setText(QCoreApplication.translate("MainWindow", u"\uc9c4\ub85c", None))
        self.radioButton_4.setText(QCoreApplication.translate("MainWindow", u"\ucc38\uc774\uc2ac", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"\uc8fc\ub958", None))
    # retranslateUi

